### ISSUE TITLE
Implement page navigation

### ISSUE THREAD

**Issue by sarahdagger** [ubclaunchpad/Footprint#9]

**Comment by mebesius** [comment]
Hey @SarahBornais, I was trying to publish my work I did on a local branch to GitHub so that everyone could see how navigation is coming along (almost there but instantiating the top-level `AppNavigator` in `App.js` results in a white screen of death right now), but I get a permission denied error.

I double-checked that I was a member of the Launch Pad repo and of Footprint, which I am. As you can see below, I am on my local branch `page-navigation` and am trying to push my work to GitHub to a new branch with the same name. 

![image](https://user-images.githubusercontent.com/38874722/68076186-a2bc7380-fd6e-11e9-884c-67e54a9ab868.png)

In terms of the ticket, once I figure out how to fix the `AppNavigator` instantiation problem, I will add try to add tests as well. Some of my thoughts as to why it currently does not work are that I might need to make an asynchronous call to load some resources perhaps or that I unknowingly created an infinite loop.

Hope everyone has a great meeting 🎃, wish I could make it.

**Comment by sarahdagger** [comment]
@mebesius I gave you write access, so you should be able to push now!

**Comment by mebesius** [comment]
@SarahBornais, thank you! It is up now 👍
